# Generated by Django 5.0.4 on 2024-04-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Nacionalidad',
            new_name='Nacionalidades',
        ),
        migrations.RenameModel(
            old_name='Posicion',
            new_name='Posiciones',
        ),
    ]
