# Generated by Django 5.0.4 on 2024-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicione',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Cierre'), ('a', 'Ala'), ('pi', 'Pivot'), ('p', 'Portera')], default='c', help_text='Posición', max_length=2),
        ),
    ]
