# Generated by Django 5.0.4 on 2024-04-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_categoria_jugadoras_remove_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadora',
            name='Categoría',
        ),
        migrations.RemoveField(
            model_name='jugadora',
            name='Posición',
        ),
        migrations.RemoveField(
            model_name='jugadora',
            name='posicion',
        ),
    ]
