# Generated by Django 5.0.4 on 2024-04-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_jugadora_categoría_remove_jugadora_posición_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='Sin categoría', help_text='Ingrese las categorias de las jugadoras', max_length=200),
        ),
        migrations.AddField(
            model_name='jugadora',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.categoria'),
        ),
        migrations.AddField(
            model_name='jugadora',
            name='posicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.posicione'),
        ),
        migrations.AddField(
            model_name='posicione',
            name='nombre',
            field=models.CharField(default='Sin posición', help_text='Ingrese las posiciones de las jugadoras', max_length=200),
        ),
        migrations.AlterField(
            model_name='nacionalidade',
            name='nombre',
            field=models.CharField(help_text='Ingrese las nacionalidades de las jugadoras', max_length=200),
        ),
    ]
