# Generated by Django 5.0.4 on 2024-04-16 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_jugadora_dorsal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaJugadora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('jugadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.jugadora')),
            ],
        ),
    ]
