# Generated by Django 5.0.4 on 2024-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_instanciajugadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadora',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='img_jugadoras'),
        ),
    ]
