# Generated by Django 5.0.4 on 2024-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_jugadora_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='imagen',
            field=models.CharField(default='/static/media/img_jugadoras/celia.PNG', max_length=200),
        ),
    ]
